services:

  backend:
    build: ./backend
    command: uvicorn app.app:app --proxy-headers --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    environment:
      - MONGO_LINK = mongodb+srv://{username}:{password}@daysmatter.gzrfyzd.mongodb.net/

  frontend:
    build: ./frontend/days-matter
    ports:
      - "3000:3000"
    depends_on:
      - backend
